using Domain.Entities;
using Domain.Interfaces.Repositories;
using System.Reflection.Emit;

namespace Infrastructure.DataAccess.Repositories
{
    public class QuestionRepository : IQuestionRepository
    {
        private List<Question> _questions;

        public QuestionRepository()
        {
            _questions = new List<Question>() {
                new Question() { Id = 1, CategoryId = 1, Text = "What is the best age to be? Why?" },
                new Question() { Id = 2, CategoryId = 1, Text = "What's been your favorite age so far in your life? Why?" },
                new Question() { Id = 3, CategoryId = 1, Text = "Do you have any fears about getting older? What are they?" },
                new Question() { Id = 4, CategoryId = 1, Text = "Who is the oldest person that you know? Are you close to him/her?" },
                new Question() { Id = 5, CategoryId = 1, Text = "Is age important in your culture?" },
                new Question() { Id = 6, CategoryId = 1, Text = "Can people of different ages be friends?" },
                new Question() { Id = 7, CategoryId = 1, Text = "Are you friends with someone much older or younger than you?" },
                new Question() { Id = 8, CategoryId = 1, Text = "What are some of your earliest memories?" },
                new Question() { Id = 9, CategoryId = 1, Text = "What was the hardest part about growing up for you?" },
                new Question() { Id = 10, CategoryId = 1, Text = "What advice would you give to your younger self?" },
                new Question() { Id = 11, CategoryId = 1, Text = "What do you think of nursing homes? Are they a nice option for older people or should they live with family members?" },
                new Question() { Id = 12, CategoryId = 1, Text = "What is a good age to 'settle down' and get married?" },
                new Question() { Id = 13, CategoryId = 1, Text = "Should younger people respect the elderly? Why or why not?" },
                new Question() { Id = 14, CategoryId = 1, Text = "Where you're from, is it okay to ask people about their age?" },
                new Question() { Id = 15, CategoryId = 1, Text = "Should job applicants be required to disclose their age to potential employers?" },

                new Question() { Id = 16, CategoryId = 2, Text = "Do you like animals? Which ones?" },
                new Question() { Id = 17, CategoryId = 2, Text = "Do you have any pets?" },
                new Question() { Id = 18, CategoryId = 2, Text = "Did you have any pets when you were younger?" },
                new Question() { Id = 19, CategoryId = 2, Text = "Some people spend thousands of dollars on their pets, especially when they get sick. What are your thoughts about this?" },
                new Question() { Id = 20, CategoryId = 2, Text = "Do you have a favorite animal?" },
                new Question() { Id = 21, CategoryId = 2, Text = "Are you afraid of any animals?" },
                new Question() { Id = 22, CategoryId = 2, Text = "Why do you think so many people are scared of sharks? Should they be scared of them?" },
                new Question() { Id = 23, CategoryId = 2, Text = "Have you seen any movies or read any books lately that featured animals in them?" },
                new Question() { Id = 24, CategoryId = 2, Text = "What do you think about zoos?" },
                new Question() { Id = 25, CategoryId = 2, Text = "What are your thoughts about eating meat raised on factory farms?" },
                new Question() { Id = 26, CategoryId = 2, Text = "Should people be allowed to eat wild animals like snakes, whales, etc.?" },
                new Question() { Id = 27, CategoryId = 2, Text = "Have you ever tried any of the new, plant-based meats like the Beyond Burger? What did you think about it?" },
                new Question() { Id = 28, CategoryId = 2, Text = "Is it necessary to use animals in product testing? Or, are there other alternatives?" },
                new Question() { Id = 29, CategoryId = 2, Text = "Should humans be doing more to ensure that animals don't become extinct?" },
                new Question() { Id = 30, CategoryId = 2, Text = "Do you think humans evolved from animals like chimpanzees?" },

                new Question() { Id = 31, CategoryId = 3, Text = "What is the first thing you notice when you meet someone?" },
                new Question() { Id = 32, CategoryId = 3, Text = "What are some factors in judging someone's appearance?" },
                new Question() { Id = 33, CategoryId = 3, Text = "What are some different types of hairstyles for men and women that are popular in your country?" },
                new Question() { Id = 34, CategoryId = 3, Text = "How often do you get your hair cut?" },
                new Question() { Id = 35, CategoryId = 3, Text = "Have you ever had a pedicure or a manicure?" },
                new Question() { Id = 36, CategoryId = 3, Text = "What do you think about waxing? Have you ever done it?" },
                new Question() { Id = 37, CategoryId = 3, Text = "How much time do you spend getting ready for work or school?" },
                new Question() { Id = 38, CategoryId = 3, Text = "Do you take pride in your appearance or not worry too much about it?" },
                new Question() { Id = 39, CategoryId = 3, Text = "What would you do if you noticed someone had food in their teeth or their 'fly' was undone?" },
                new Question() { Id = 40, CategoryId = 3, Text = "What kinds of clothes do you like to wear?" },
                new Question() { Id = 41, CategoryId = 3, Text = "Do you have a favorite article of clothing?" },
                new Question() { Id = 42, CategoryId = 3, Text = "How much money do you spend on clothes and shoes each month?" },
                new Question() { Id = 43, CategoryId = 3, Text = "What do you think about young girls wearing makeup?" },
                new Question() { Id = 44, CategoryId = 3, Text = "What about makeup for men?" },
                new Question() { Id = 45, CategoryId = 3, Text = "What are your thoughts about photos on job applications?" },

                new Question() { Id = 46, CategoryId = 4, Text = "What do you like about where you live?" },
                new Question() { Id = 47, CategoryId = 4, Text = "What do you dislike about where you live?" },
                new Question() { Id = 48, CategoryId = 4, Text = "Would you like to move somewhere else? Or, are you happy with where you live?" },
                new Question() { Id = 49, CategoryId = 4, Text = "What are some reasons that people might move to your neighborhood?" },
                new Question() { Id = 50, CategoryId = 4, Text = "Are there any famous areas or sights near where you live?" },
                new Question() { Id = 51, CategoryId = 4, Text = "What are some things to do around your house?" },
                new Question() { Id = 52, CategoryId = 4, Text = "What are some of your favorite restaurants near your house?" },
                new Question() { Id = 53, CategoryId = 4, Text = "If you want to get a cheap, quick lunch near your home, where do you go?" },
                new Question() { Id = 54, CategoryId = 4, Text = "Can you walk to do shopping in your neighborhood or do you have to drive to pick up most things?" },
                new Question() { Id = 55, CategoryId = 4, Text = "Do you need a car to get around your town or is the public transport system adequate?" },
                new Question() { Id = 56, CategoryId = 4, Text = "What are five adjectives you'd use to describe your neighborhood (busy, quiet, etc.)?" },
                new Question() { Id = 57, CategoryId = 4, Text = "Do you know your neighbors? What are they like?" },
                new Question() { Id = 58, CategoryId = 4, Text = "What are three things you'd like to do to improve your neighborhood?" },
                new Question() { Id = 59, CategoryId = 4, Text = "Did you grow up where you live now? If not, how do they compare?" },
                new Question() { Id = 60, CategoryId = 4, Text = "When you go out at night or on the weekend, do you stick close to home or do you travel to another part of your city?" },

                new Question() { Id = 61, CategoryId = 5, Text = "Do you paint, draw, or take pictures (or do some other kind of art)?" },
                new Question() { Id = 62, CategoryId = 5, Text = "Did you enjoy art class in school when you were a kid?" },
                new Question() { Id = 63, CategoryId = 5, Text = "Should things like art class be mandatory until the end of high school? In most countries, it's optional after elementary school." },
                new Question() { Id = 64, CategoryId = 5, Text = "Is art important to you? Why or why not?" },
                new Question() { Id = 65, CategoryId = 5, Text = "Should artists be funded by the government?" },
                new Question() { Id = 66, CategoryId = 5, Text = "Why do you think people pay millions of dollars for some famous paintings or sculptures?" },
                new Question() { Id = 67, CategoryId = 5, Text = "If you had lots of money, would you spend it buying expensive pieces of art?" },
                new Question() { Id = 68, CategoryId = 5, Text = "What would you think if you had a son or daughter who wanted to go to art school instead of university?" },
                new Question() { Id = 69, CategoryId = 5, Text = "Can art teach us things about life?" },
                new Question() { Id = 70, CategoryId = 5, Text = "Have you ever been influenced by a piece of art?" },
                new Question() { Id = 71, CategoryId = 5, Text = "Do you think movies and TV shows are a form of art?" },
                new Question() { Id = 72, CategoryId = 5, Text = "Is graffiti 'real' art?" },
                new Question() { Id = 73, CategoryId = 5, Text = "Is fashion/clothing art?" },
                new Question() { Id = 74, CategoryId = 5, Text = "When was the last time you went to a museum?" },
                new Question() { Id = 75, CategoryId = 5, Text = "Do you generally like going to museums? Why or why not?" },

                new Question() { Id = 76, CategoryId = 6, Text = "Are birthdays important to you? Why or why not?" },
                new Question() { Id = 77, CategoryId = 6, Text = "How are birthdays usually celebrated in your country?" },
                new Question() { Id = 78, CategoryId = 6, Text = "How do young kids celebrate their birthday at school in your country?" },
                new Question() { Id = 79, CategoryId = 6, Text = "Have you ever thrown a surprise birthday party or had one thrown for you?" },
                new Question() { Id = 80, CategoryId = 6, Text = "Have you ever forgotten an important birthday of someone close to you?" },
                new Question() { Id = 81, CategoryId = 6, Text = "Do you have a memorable past birthday memory? What made it memorable?" },
                new Question() { Id = 82, CategoryId = 6, Text = "Do you have any bad birthday memories? What happened?" },
                new Question() { Id = 83, CategoryId = 6, Text = "Do you prefer to organize your own birthday party or have someone else organize it for you?" },
                new Question() { Id = 84, CategoryId = 6, Text = "Are birthdays in your family important? How do you celebrate them?" },
                new Question() { Id = 85, CategoryId = 6, Text = "What do you think about elaborate, expensive birthday parties for little kids (1-5 years old)?" },
                new Question() { Id = 86, CategoryId = 6, Text = "Do you think turning 40, 50, or 60 is exciting or depressing? Or, some other adjective?" },
                new Question() { Id = 87, CategoryId = 6, Text = "What are some memorable birthday presents that you've received?" },
                new Question() { Id = 88, CategoryId = 6, Text = "How much do you usually spend on a birthday present for a family member?" },
                new Question() { Id = 89, CategoryId = 6, Text = "What do you think about birthday cards? Nice, or a waste of money?" },
                new Question() { Id = 90, CategoryId = 6, Text = "Does anyone famous have the same birthday as you? Or a friend or family member?" },

                new Question() { Id = 91, CategoryId = 7, Text = "On average, how many books do you read in a month?" },
                new Question() { Id = 92, CategoryId = 7, Text = "Do you usually buy books or go to the library?" },
                new Question() { Id = 93, CategoryId = 7, Text = "When do you usually read?" },
                new Question() { Id = 94, CategoryId = 7, Text = "What is your favorite genre of books?" },
                new Question() { Id = 95, CategoryId = 7, Text = "Do you prefer fiction or non-fiction?" },
                new Question() { Id = 96, CategoryId = 7, Text = "Is there a book that has had a big impact on your life?" },
                new Question() { Id = 97, CategoryId = 7, Text = "Are there any books or authors that you'd recommend?" },
                new Question() { Id = 98, CategoryId = 7, Text = "Do you like watching TV or movies more than reading books?" },
                new Question() { Id = 99, CategoryId = 7, Text = "Have you ever been part of a book club? What was that experience like?" },
                new Question() { Id = 100, CategoryId = 7, Text = "Did you like reading books for school?" },
                new Question() { Id = 101, CategoryId = 7, Text = "Have you ever been to a book signing event or met an author?" },
                new Question() { Id = 102, CategoryId = 7, Text = "Have you ever thought about writing a book? What about?" },
                new Question() { Id = 103, CategoryId = 7, Text = "What do you think about books made into movies? Which version is usually better?" },
                new Question() { Id = 104, CategoryId = 7, Text = "How do you choose a book to read?" },
                new Question() { Id = 105, CategoryId = 7, Text = "Did you have any favorite books from when you were a kid that you can remember?" },

                new Question() { Id = 106, CategoryId = 8, Text ="Are there any companies that you love to support? Why?" },
                new Question() { Id = 107, CategoryId = 8, Text ="Are there any companies that you choose not to support? Why?" },
                new Question() { Id = 108, CategoryId = 8, Text ="Have you had any bad customer service experiences? Talk about 1-2 of them." },
                new Question() { Id = 109, CategoryId = 8, Text ="Do you like to support small businesses?" },
                new Question() { Id = 110, CategoryId = 8, Text ="Are there any new businesses in your neighborhood that you've noticed lately?" },
                new Question() { Id = 111, CategoryId = 8, Text ="Do you know anyone with their own business? Describe it." },
                new Question() { Id = 112, CategoryId = 8, Text ="What are some advantages and disadvantages of working for yourself?" },
                new Question() { Id = 113, CategoryId = 8, Text ="Is the 'gig economy' a big thing in your country? (gig economy is when people do freelance or contract work)" },
                new Question() { Id = 114, CategoryId = 8, Text ="Would you rather work for someone or work for yourself?" },
                new Question() { Id = 115, CategoryId = 8, Text ="Should the government 'bail out' big business during a recession? Why or why not?" },
                new Question() { Id = 116, CategoryId = 8, Text ="Together, name 5 slogans from companies that you know (Just do it!)." },
                new Question() { Id = 117, CategoryId = 8, Text ="Does every business need a website these days?" },
                new Question() { Id = 118, CategoryId = 8, Text ="If you could work abroad, would you choose to do it?" },
                new Question() { Id = 119, CategoryId = 8, Text ="What are some qualities of a good company CEO or owner?" },
                new Question() { Id = 120, CategoryId = 8, Text ="What business do well during a recession? Which ones struggle?" },

                new Question() { Id = 121, CategoryId = 9, Text ="What are some advantages and disadvantages to having your own car?" },
                new Question() { Id = 122, CategoryId = 9, Text ="What are some advantages and disadvantages to public transportation?" },
                new Question() { Id = 123, CategoryId = 9, Text ="How do most people get to work or school in your country?" },
                new Question() { Id = 124, CategoryId = 9, Text ="How do you get to work or school?" },
                new Question() { Id = 125, CategoryId = 9, Text ="Do you have a driver's license?" },
                new Question() { Id = 126, CategoryId = 9, Text ="When did you start driving?" },
                new Question() { Id = 127, CategoryId = 9, Text ="Have you ever been in a car accident?" },
                new Question() { Id = 128, CategoryId = 9, Text ="How would you describe yourself as a driver? (aggressive, cautious, etc.)" },
                new Question() { Id = 129, CategoryId = 9, Text ="When do you usually drive?" },
                new Question() { Id = 130, CategoryId = 9, Text ="Is there a certain car that you'd like to buy in the future?" },
                new Question() { Id = 131, CategoryId = 9, Text ="Have you ever considered buying an electric car?" },
                new Question() { Id = 132, CategoryId = 9, Text ="Do you have any predictions for what cars will look like in the future?" },
                new Question() { Id = 133, CategoryId = 9, Text ="Should the government ban 'gas guzzlers'?" },
                new Question() { Id = 134, CategoryId = 9, Text ="Should there be mandatory emissions tests on cars every few years?" },
                new Question() { Id = 135, CategoryId = 9, Text ="Will the use of cars increase or decrease in the future? Why?" },

                new Question() { Id = 136, CategoryId = 10, Text ="What are some of your favorite memories from childhood?" },
                new Question() { Id = 137, CategoryId = 10, Text ="Do you have any brothers or sisters? What did you like to do together growing up?" },
                new Question() { Id = 138, CategoryId = 10, Text ="Do you remember any teachers from when you were younger? What were they like?" },
                new Question() { Id = 139, CategoryId = 10, Text ="What was your favorite subject in school?" },
                new Question() { Id = 140, CategoryId = 10, Text ="What was your least favorite subject in school?" },
                new Question() { Id = 141, CategoryId = 10, Text ="What was a memorable field trip you took when you were young?" },
                new Question() { Id = 142, CategoryId = 10, Text ="What was a memorable vacation you took with your family when you were younger?" },
                new Question() { Id = 143, CategoryId = 10, Text ="What was your favorite food growing up?" },
                new Question() { Id = 144, CategoryId = 10, Text ="Were there foods you didn't like when you were younger? Do you still dislike them?" },
                new Question() { Id = 145, CategoryId = 10, Text ="Did you have a best friend growing up? Are you still in touch?" },
                new Question() { Id = 146, CategoryId = 10, Text ="What was the house you grew up in like?" },
                new Question() { Id = 147, CategoryId = 10, Text ="Did you move during your childhood? Was that a difficult experience?" },
                new Question() { Id = 148, CategoryId = 10, Text ="Did you play any sports or do any activities during childhood?" },
                new Question() { Id = 149, CategoryId = 10, Text ="Do you have mostly positive or negative memories from when you were a kid?" },
                new Question() { Id = 150, CategoryId = 10, Text ="Did you spend most of your time playing inside or outside when you were young?" },

                new Question() { Id = 151, CategoryId = 11, Text ="Name 10 chores around the house." },
                new Question() { Id = 152, CategoryId = 11, Text ="What chores did you have to do when you were a kid?" },
                new Question() { Id = 153, CategoryId = 11, Text ="Did you get paid for doing chores or did you get an allowance?" },
                new Question() { Id = 154, CategoryId = 11, Text ="What chores do you spend a lot of time doing these days?" },
                new Question() { Id = 155, CategoryId = 11, Text ="What are some chores that you don't mind or enjoy doing?" },
                new Question() { Id = 156, CategoryId = 11, Text ="What are some chores that you hate?" },
                new Question() { Id = 157, CategoryId = 11, Text ="Is there a way to make chores fun?" },
                new Question() { Id = 158, CategoryId = 11, Text ="Do you tackle things quickly to get them over with or procrastinate for things you don't want to do?" },
                new Question() { Id = 159, CategoryId = 11, Text ="Do you have kids? If yes, what chores are they responsible for?" },
                new Question() { Id = 160, CategoryId = 11, Text ="Do your kids get to choose what chores they do?" },
                new Question() { Id = 161, CategoryId = 11, Text ="Do you prefer doing laundry all at once or a load every few days?" },
                new Question() { Id = 162, CategoryId = 11, Text ="Do you wash your dishes and clean up the kitchen after every meal?" },
                new Question() { Id = 163, CategoryId = 11, Text ="How often do you vacuum and clean the floors at your house?" },
                new Question() { Id = 164, CategoryId = 11, Text ="How often do you clean the bathroom at your house?" },
                new Question() { Id = 165, CategoryId = 11, Text ="How often do you wash and clean your car?" },

                new Question() { Id = 166, CategoryId = 12, Text ="Is how you dress important to you?" },
                new Question() { Id = 167, CategoryId = 12, Text ="Where do you usually buy clothes?" },
                new Question() { Id = 168, CategoryId = 12, Text ="Do you like shopping at thrift stores for clothes? Why or why not?" },
                new Question() { Id = 169, CategoryId = 12, Text ="What are 2-3 of your favorite articles of clothing?" },
                new Question() { Id = 170, CategoryId = 12, Text ="Have you ever made your own clothes?" },
                new Question() { Id = 171, CategoryId = 12, Text ="How often do you go shopping for clothes?" },
                new Question() { Id = 172, CategoryId = 12, Text ="In one year, how much do you think you spend on clothes and shoes? Would you spend more if you could afford it?" },
                new Question() { Id = 173, CategoryId = 12, Text ="What are some of the advantages and disadvantages of shopping online?" },
                new Question() { Id = 174, CategoryId = 12, Text ="What are some of the advantages and disadvantages of shopping in stores?" },
                new Question() { Id = 175, CategoryId = 12, Text ="What do you think about the price of designer clothes, shoes, and bags?" },
                new Question() { Id = 176, CategoryId = 12, Text ="What's the most you've ever spent on a single piece of clothing? Do you regret it?" },
                new Question() { Id = 177, CategoryId = 12, Text ="Do you follow clothing trends?" },
                new Question() { Id = 178, CategoryId = 12, Text ="What are some strange fashion trends that you've seen?" },
                new Question() { Id = 179, CategoryId = 12, Text ="How would you describe your fashion sense and style?" },
                new Question() { Id = 180, CategoryId = 12, Text ="What do you think about people dressing up their dogs in cute outfits?" },

                new Question() { Id = 181, CategoryId = 13, Text ="What are 10 forms of communication?" },
                new Question() { Id = 182, CategoryId = 13, Text ="Which ones existed 50 years ago?" },
                new Question() { Id = 183, CategoryId = 13, Text ="How do you usually stay in touch with friends?" },
                new Question() { Id = 184, CategoryId = 13, Text ="How do you stay in touch with family members?" },
                new Question() { Id = 185, CategoryId = 13, Text ="How do you communicate with classmates, teachers, or coworkers?" },
                new Question() { Id = 186, CategoryId = 13, Text ="Do you consider yourself to be a 'techie'?" },
                new Question() { Id = 187, CategoryId = 13, Text ="Has communication changed between people 50 years ago compared to now?" },
                new Question() { Id = 188, CategoryId = 13, Text ="Do you generally chat with people you don't know (taxi driver, shop keeper, etc.)?" },
                new Question() { Id = 189, CategoryId = 13, Text ="Where are some good places to meet new people in your country?" },
                new Question() { Id = 190, CategoryId = 13, Text ="Do you prefer meeting people in person or online?" },
                new Question() { Id = 191, CategoryId = 13, Text ="Do you have some online-only friends?" },
                new Question() { Id = 192, CategoryId = 13, Text ="Do you know anyone who doesn't have a smartphone? What is their reason for this?" },
                new Question() { Id = 193, CategoryId = 13, Text ="What do you think communication will look like 50 years from now?" },
                new Question() { Id = 194, CategoryId = 13, Text ="Do you think we can communicate with people from the past (ghosts, spirits, etc.)" },
                new Question() { Id = 195, CategoryId = 13, Text ="If you have a serious thing to talk about with someone, do you prefer sending them an email (or other written thing) or talking face to face?" },

                new Question() { Id = 196, CategoryId = 14, Text ="What are 10 adjectives to describe communities (vibrant, active, etc.)?" },
                new Question() { Id = 197, CategoryId = 14, Text ="How would you describe where you live?" },
                new Question() { Id = 198, CategoryId = 14, Text ="Is there anything you would like to see change in your neighborhood or city?" },
                new Question() { Id = 199, CategoryId = 14, Text ="What are the things you like most about where you live?" },
                new Question() { Id = 200, CategoryId = 14, Text ="Are there mostly older or younger people where you live?" },
                new Question() { Id = 201, CategoryId = 14, Text ="Are there lots of recreational opportunities where you live?" },
                new Question() { Id = 202, CategoryId = 14, Text ="Are there lots of job opportunities in your community or do people mostly commute somewhere else?" },
                new Question() { Id = 203, CategoryId = 14, Text ="Have you done something recently to help one of your neighbors?" },
                new Question() { Id = 204, CategoryId = 14, Text ="How well do you know your neighbors?" },
                new Question() { Id = 205, CategoryId = 14, Text ="What different communities are you a part of? (work, family, friend group, neighborhood, clubs, etc.)" },
                new Question() { Id = 206, CategoryId = 14, Text ="Which of those communities is most important to you?" },
                new Question() { Id = 207, CategoryId = 14, Text ="Which one do you spend the most time with?" },
                new Question() { Id = 208, CategoryId = 14, Text ="Where do you find it easiest to make new friends?" },
                new Question() { Id = 209, CategoryId = 14, Text ="Have you found it difficult to make new friends where you live compared to other places?" },
                new Question() { Id = 210, CategoryId = 14, Text ="Is community life important to you when choosing a new place to live?" },

                new Question() { Id = 211, CategoryId = 15, Text ="Are there any controversial things in the news lately?" },
                new Question() { Id = 212, CategoryId = 15, Text ="What do you think about animal testing on cosmetics or new medicines?" },
                new Question() { Id = 213, CategoryId = 15, Text ="What do you think about gay marriage (also called marriage equality)?" },
                new Question() { Id = 214, CategoryId = 15, Text ="Should women be paid the same amount as men for the same job?" },
                new Question() { Id = 215, CategoryId = 15, Text ="Should smoking be banned in this country?" },
                new Question() { Id = 216, CategoryId = 15, Text ="Should the government increase taxes on 'luxury' items like cigarettes, alcohol, expensive cars, or designer clothing?" },
                new Question() { Id = 217, CategoryId = 15, Text ="Should marijuana or other recreational drugs be legalized?" },
                new Question() { Id = 218, CategoryId = 15, Text ="Should teenagers have strict curfews and other rules?" },
                new Question() { Id = 219, CategoryId = 15, Text ="Should elementary school students be given homework?" },
                new Question() { Id = 220, CategoryId = 15, Text ="Assisted suicide should be legalized for the terminally ill. Do you agree or disagree?" },
                new Question() { Id = 221, CategoryId = 15, Text ="Do you think video games contribute to violence in society?" },
                new Question() { Id = 222, CategoryId = 15, Text ="Should guns be banned?" },
                new Question() { Id = 223, CategoryId = 15, Text ="Should the death penalty be allowed?" },
                new Question() { Id = 224, CategoryId = 15, Text ="What do you think about religion? Helpful or harmful?" },
                new Question() { Id = 225, CategoryId = 15, Text ="Do you think it's better for women to not get married?" },

                new Question() { Id = 226, CategoryId = 16, Text ="In one week, how often do you eat out?" },
                new Question() { Id = 227, CategoryId = 16, Text ="In one week, how often do you get take out?" },
                new Question() { Id = 228, CategoryId = 16, Text ="Do you enjoy cooking at home?" },
                new Question() { Id = 229, CategoryId = 16, Text ="Would you consider yourself to be a good cook?" },
                new Question() { Id = 230, CategoryId = 16, Text ="What are some of the meals you regularly eat?" },
                new Question() { Id = 231, CategoryId = 16, Text ="Do you like cooking with meat? Are you a vegan or have any other dietary restrictions?" },
                new Question() { Id = 232, CategoryId = 16, Text ="Do you have any favorite kitchen appliances?" },
                new Question() { Id = 233, CategoryId = 16, Text ="Do you do anything special for weekend breakfasts?" },
                new Question() { Id = 234, CategoryId = 16, Text ="What are some special things you cook if someone is coming over for dinner?" },
                new Question() { Id = 235, CategoryId = 16, Text ="How often do you invite someone over for a meal at your house?" },
                new Question() { Id = 236, CategoryId = 16, Text ="Do you enjoy cooking a big holiday or family meal or do you find it stressful?" },
                new Question() { Id = 237, CategoryId = 16, Text ="What are some of the first things you learned how to cook when you were a kid?" },
                new Question() { Id = 238, CategoryId = 16, Text ="Would you say that most of your meals are healthy or unhealthy?" },
                new Question() { Id = 239, CategoryId = 16, Text ="Who does most of the grocery shopping and cooking at your house?" },
                new Question() { Id = 240, CategoryId = 16, Text ="What do you think about meal prep boxes where you get all the ingredients and a recipe but have to cook it yourself? Are they popular where you live?" },

                new Question() { Id = 241, CategoryId = 17, Text ="Is Christmas a popular holiday in your country?" },
                new Question() { Id = 242, CategoryId = 17, Text ="Do you have any memories from Christmas holidays when you were a kid?" },
                new Question() { Id = 243, CategoryId = 17, Text ="Do you enjoy giving or getting Christmas presents?" },
                new Question() { Id = 244, CategoryId = 17, Text ="Does your family get together at Christmas?" },
                new Question() { Id = 245, CategoryId = 17, Text ="Do you like to eat any sort of special food for Christmas?" },
                new Question() { Id = 246, CategoryId = 17, Text ="Did you believe in Santa Klaus as a kid?" },
                new Question() { Id = 247, CategoryId = 17, Text ="Is Santa Claus an innocent traditional or harmful in some way?" },
                new Question() { Id = 248, CategoryId = 17, Text ="Do you celebrate the religious aspect of Christmas?" },
                new Question() { Id = 249, CategoryId = 17, Text ="Does it usually snow where you live at Christmas?" },
                new Question() { Id = 250, CategoryId = 17, Text ="Do you know any Christmas carols? Do you enjoy singing them?" },
                new Question() { Id = 251, CategoryId = 17, Text ="Do you send Christmas cards?" },
                new Question() { Id = 252, CategoryId = 17, Text ="Did you have any memorable Christmas parties or traditions at school when you were young? " },
                new Question() { Id = 253, CategoryId = 17, Text ="Does your school or workplace have Christmas parties? What are they like?" },
                new Question() { Id = 254, CategoryId = 17, Text ="Do you put up Christmas decorations at your house?" },
                new Question() { Id = 255, CategoryId = 17, Text ="What do you think about cutting down living trees for Christmas trees in houses?" },

                new Question() { Id = 256, CategoryId = 18, Text ="What are 15 ways to describe a country?" },
                new Question() { Id = 257, CategoryId = 18, Text ="How would you describe your country?" },
                new Question() { Id = 258, CategoryId = 18, Text ="What are the major holidays in your country?" },
                new Question() { Id = 259, CategoryId = 18, Text ="Is your country known for anything special?" },
                new Question() { Id = 260, CategoryId = 18, Text ="Are there any famous foods from your country?" },
                new Question() { Id = 261, CategoryId = 18, Text ="Does your country have any strong allies?" },
                new Question() { Id = 262, CategoryId = 18, Text ="Have you ever visited another country? How did it compare to yours?" },
                new Question() { Id = 263, CategoryId = 18, Text ="Is there a country you want to visit in the future?" },
                new Question() { Id = 264, CategoryId = 18, Text ="If you could take a world tour for 6 months, where would you visit and what would you do?" },
                new Question() { Id = 265, CategoryId = 18, Text ="What do you think is the perfect length of time for a vacation?" },
                new Question() { Id = 266, CategoryId = 18, Text ="Is there another country that you'd like to live in?" },
                new Question() { Id = 267, CategoryId = 18, Text ="What's one of the best countries to live in? Why?" },
                new Question() { Id = 268, CategoryId = 18, Text ="What is a country that you wouldn't want to live in? Why?" },
                new Question() { Id = 269, CategoryId = 18, Text ="Are there some countries that are better than others or are they just different?" },
                new Question() { Id = 270, CategoryId = 18, Text ="Do you feel pride in your country during things like the World Cup or the Olympics?" },

                new Question() { Id = 271, CategoryId = 19, Text ="Do you like to follow what's happening in the news?" },
                new Question() { Id = 272, CategoryId = 19, Text ="Where do you get information about what's happening in the world?" },
                new Question() { Id = 273, CategoryId = 19, Text ="How many hours a week do you spend following current events?" },
                new Question() { Id = 274, CategoryId = 19, Text ="Is keeping up with current events important or not?" },
                new Question() { Id = 275, CategoryId = 19, Text ="Are there any podcasts that you like to listen to?" },
                new Question() { Id = 276, CategoryId = 19, Text ="Do you think that the media reports too much 'doom and gloom' and not enough of the good things?" },
                new Question() { Id = 277, CategoryId = 19, Text ="Do you think that there's a difference between news and current events?" },
                new Question() { Id = 278, CategoryId = 19, Text ="Is there any current event that you're particularly interested in right now?" },
                new Question() { Id = 279, CategoryId = 19, Text ="Do you think that newspapers are a dying industry?" },
                new Question() { Id = 280, CategoryId = 19, Text ="Should anyone be allowed to publish whatever they want on the Internet?" },
                new Question() { Id = 281, CategoryId = 19, Text ="If you go away for a few days and don't follow the news, is that a big deal to you?" },
                new Question() { Id = 282, CategoryId = 19, Text ="Do news and current events affect your mood?" },
                new Question() { Id = 283, CategoryId = 19, Text ="Did Covid-19 affect your life in any way?" },
                new Question() { Id = 284, CategoryId = 19, Text ="Do you think the news is censored where you live?" },
                new Question() { Id = 285, CategoryId = 19, Text ="Do you ever buy or read magazines?" },

                new Question() { Id = 286, CategoryId = 20, Text ="How do young people usually meet in your country?" },
                new Question() { Id = 287, CategoryId = 20, Text ="Have you ever tried online dating? How did it go?" },
                new Question() { Id = 288, CategoryId = 20, Text ="Is dating common among your friends?" },
                new Question() { Id = 289, CategoryId = 20, Text ="At what age do people usually get married where you live?" },
                new Question() { Id = 290, CategoryId = 20, Text ="Do you have any interesting experiences with dating?" },
                new Question() { Id = 291, CategoryId = 20, Text ="If you have a partner, how did you meet them?" },
                new Question() { Id = 292, CategoryId = 20, Text ="What are your thoughts about arranged marriages?" },
                new Question() { Id = 293, CategoryId = 20, Text ="What are some first date 'red flags'?" },
                new Question() { Id = 294, CategoryId = 20, Text ="Do you want to get married (if you're not already)?" },
                new Question() { Id = 295, CategoryId = 20, Text ="What are the positives and negatives of marriage in your opinion?" },
                new Question() { Id = 296, CategoryId = 20, Text ="Do you know what the divorce rate is in your country? Do you think it's high or low?" },
                new Question() { Id = 297, CategoryId = 20, Text ="Should people just stay together for their kids and not get divorced, even if they're unhappy?" },
                new Question() { Id = 298, CategoryId = 20, Text ="What are your thoughts about gay marriage?" },
                new Question() { Id = 299, CategoryId = 20, Text ="Is marriage a thing of the past?" },
                new Question() { Id = 300, CategoryId = 20, Text ="What do you think about people spending thousands of dollars on an extravagant wedding?" },


            };
        }

        public async Task<IEnumerable<Question>> GetQuestionsAsync(int categoryId)
        {
            return _questions
                .Where(q => q.CategoryId == categoryId)
                .ToList();
        }

        public Question GetQuestionById(int id)
        {
            return _questions.Single(q => q.Id == id);
        }
    }
}